# Generated by Django 6.1.2 on 2026-10-08 22:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('present', 'Present'), ('absent', 'Absent'), ('cancelled', 'Cancelled'), ('holiday', 'Holiday'), ('exam', 'Exam'), ('event', 'College Event'), ('modified', 'Modified')], default='scheduled', max_length=12)),
                ('attendance_weight', models.FloatField(default=1.0, help_text='1 for session-based; hours for period-based')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('cancelled', 'Cancelled')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_record', to='attendance.classsession')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('min_attendance', models.FloatField(default=75.0, help_text='Minimum required attendance percentage', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('safety_buffer', models.FloatField(default=5.0, help_text='Extra buffer above minimum (effective target = min + buffer)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(50.0)])),
                ('attendance_policy', models.CharField(choices=[('session', 'Session-based (each class = 1 unit regardless of duration)'), ('period', 'Period-based (each hour = 1 unit)')], default='session', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('event_type', models.CharField(choices=[('trip', 'Trip / Travel'), ('medical', 'Medical Appointment'), ('family', 'Family Function'), ('personal', 'Personal'), ('other', 'Other')], default='personal', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='attendance.semester')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.semester'),
        ),
        migrations.CreateModel(
            name='SimulationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'What if I take Friday off?'", max_length=200)),
                ('result_json', models.JSONField(help_text='Stores projected attendance per subject as JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='attendance.semester')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('day_type', models.CharField(choices=[('holiday', 'Holiday'), ('exam', 'Exam Day'), ('event', 'College Event'), ('partial', 'Partial Day'), ('custom', 'Custom')], max_length=10)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('affects_all_sessions', models.BooleanField(default=True, help_text='True = all sessions cancelled. False = use per-session overrides.')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_days', to='attendance.semester')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('semester', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SpecialDaySessionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('override_status', models.CharField(choices=[('cancelled', 'Cancelled'), ('conducted', 'Conducted as usual'), ('exam', 'Exam replaces session'), ('event', 'Event replaces session')], max_length=10)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='attendance.classsession')),
                ('special_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_overrides', to='attendance.specialday')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('subject_type', models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab / Practical'), ('tutorial', 'Tutorial'), ('other', 'Other')], default='lecture', max_length=10)),
                ('min_attendance', models.FloatField(blank=True, help_text='Leave blank to use semester default', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('color', models.CharField(default='#4f46e5', help_text='Hex color for UI', max_length=7)),
                ('icon', models.CharField(default='📚', help_text='Emoji icon', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='attendance.semester')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('semester', 'code')},
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.subject'),
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=50)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='attendance.semester')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='attendance.subject')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='classsession',
            name='timetable_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='attendance.timetableentry'),
        ),
        migrations.CreateModel(
            name='PlannedAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('is_confirmed', models.BooleanField(default=False, help_text='False = simulation/what-if. True = student has confirmed this absence.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_absences', to='attendance.classsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_absences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='classsession',
            unique_together={('semester', 'subject', 'timetable_entry', 'date')},
        ),
    ]
