# Generated by Django 6.1.2 on 2026-10-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classsession',
            name='session_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab / Practical'), ('tutorial', 'Tutorial'), ('other', 'Other')], default='lecture', max_length=10),
        ),
        migrations.AddField(
            model_name='subject',
            name='has_lab',
            field=models.BooleanField(default=False, help_text='Enable if this subject includes lab / practical sessions'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='session_type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('lab', 'Lab / Practical'), ('tutorial', 'Tutorial'), ('other', 'Other')], default='lecture', max_length=10),
        ),
    ]
